---
- name: Checkout repo
  git:
    repo: git@github.com:{{ repo_name }}.git
    accept_hostkey: true
    dest: "{{ repo_folder }}"
    version: "{{ repo_branch }}"

    key_file: /home/optimus/.ssh/id_ed25519
    force: true
