---

- name: Update packages
  ansible.builtin.apt:
    update_cache: yes

- name: Install required system packages
  ansible.builtin.apt:
    name: "{{ sys_packages }}"
    state: "latest"

- name: Create Server SSL certificate
  community.crypto.openssl_privatekey:
    path: "/etc/ssl/private/{{server_name}}.key"
    type: RSA

- name: Create simple self-signed certificate
  community.crypto.x509_certificate:
    path: "/etc/ssl/certs/{{server_name}}.pem"
    privatekey_path: "/etc/ssl/private/{{server_name}}.key"
    provider: selfsigned

